# coding: utf-8

"""
    Habitat repository and authorization API

    Habitat API  # noqa: E501

    OpenAPI spec version: V1.1.0
    Contact: zives@seas.upenn.edu
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from pennprov.models.tuple_with_schema_model import TupleWithSchemaModel  # noqa: F401,E501


class LinkInstance(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'source_id': 'str',
        'target_id': 'str',
        'type': 'str',
        'tuple': 'TupleWithSchemaModel'
    }

    attribute_map = {
        'source_id': 'sourceId',
        'target_id': 'targetId',
        'type': 'type',
        'tuple': 'tuple'
    }

    def __init__(self, source_id=None, target_id=None, type=None, tuple=None):  # noqa: E501
        """LinkInstance - a model defined in Swagger"""  # noqa: E501

        self._source_id = None
        self._target_id = None
        self._type = None
        self._tuple = None
        self.discriminator = None

        if source_id is not None:
            self.source_id = source_id
        if target_id is not None:
            self.target_id = target_id
        if type is not None:
            self.type = type
        if tuple is not None:
            self.tuple = tuple

    @property
    def source_id(self):
        """Gets the source_id of this LinkInstance.  # noqa: E501


        :return: The source_id of this LinkInstance.  # noqa: E501
        :rtype: str
        """
        return self._source_id

    @source_id.setter
    def source_id(self, source_id):
        """Sets the source_id of this LinkInstance.


        :param source_id: The source_id of this LinkInstance.  # noqa: E501
        :type: str
        """

        self._source_id = source_id

    @property
    def target_id(self):
        """Gets the target_id of this LinkInstance.  # noqa: E501


        :return: The target_id of this LinkInstance.  # noqa: E501
        :rtype: str
        """
        return self._target_id

    @target_id.setter
    def target_id(self, target_id):
        """Sets the target_id of this LinkInstance.


        :param target_id: The target_id of this LinkInstance.  # noqa: E501
        :type: str
        """

        self._target_id = target_id

    @property
    def type(self):
        """Gets the type of this LinkInstance.  # noqa: E501


        :return: The type of this LinkInstance.  # noqa: E501
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this LinkInstance.


        :param type: The type of this LinkInstance.  # noqa: E501
        :type: str
        """

        self._type = type

    @property
    def tuple(self):
        """Gets the tuple of this LinkInstance.  # noqa: E501


        :return: The tuple of this LinkInstance.  # noqa: E501
        :rtype: TupleWithSchemaModel
        """
        return self._tuple

    @tuple.setter
    def tuple(self, tuple):
        """Sets the tuple of this LinkInstance.


        :param tuple: The tuple of this LinkInstance.  # noqa: E501
        :type: TupleWithSchemaModel
        """

        self._tuple = tuple

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, LinkInstance):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
