# coding: utf-8

"""
    Habitat repository and authorization API

    Habitat API  # noqa: E501

    OpenAPI spec version: V1.1.0
    Contact: zives@seas.upenn.edu
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from pennprov.models.prov_specifier_model import ProvSpecifierModel  # noqa: F401,E501


class ProvExpressionModel(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'operation': 'str',
        'operands': 'list[ProvSpecifierModel]'
    }

    attribute_map = {
        'operation': 'operation',
        'operands': 'operands'
    }

    def __init__(self, operation=None, operands=None):  # noqa: E501
        """ProvExpressionModel - a model defined in Swagger"""  # noqa: E501

        self._operation = None
        self._operands = None
        self.discriminator = None

        self.operation = operation
        if operands is not None:
            self.operands = operands

    @property
    def operation(self):
        """Gets the operation of this ProvExpressionModel.  # noqa: E501


        :return: The operation of this ProvExpressionModel.  # noqa: E501
        :rtype: str
        """
        return self._operation

    @operation.setter
    def operation(self, operation):
        """Sets the operation of this ProvExpressionModel.


        :param operation: The operation of this ProvExpressionModel.  # noqa: E501
        :type: str
        """
        if operation is None:
            raise ValueError("Invalid value for `operation`, must not be `None`")  # noqa: E501

        self._operation = operation

    @property
    def operands(self):
        """Gets the operands of this ProvExpressionModel.  # noqa: E501


        :return: The operands of this ProvExpressionModel.  # noqa: E501
        :rtype: list[ProvSpecifierModel]
        """
        return self._operands

    @operands.setter
    def operands(self, operands):
        """Sets the operands of this ProvExpressionModel.


        :param operands: The operands of this ProvExpressionModel.  # noqa: E501
        :type: list[ProvSpecifierModel]
        """

        self._operands = operands

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ProvExpressionModel):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
