# coding: utf-8

"""
    Habitat repository and authorization API

    Habitat API  # noqa: E501

    OpenAPI spec version: V1.1.0
    Contact: zives@seas.upenn.edu
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from pennprov.models.link_info import LinkInfo  # noqa: F401,E501
from pennprov.models.node_info import NodeInfo  # noqa: F401,E501


class SubgraphTemplate(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'ranks': 'list[list[NodeInfo]]',
        'links': 'list[LinkInfo]',
        'order_by': 'list[str]'
    }

    attribute_map = {
        'ranks': 'ranks',
        'links': 'links',
        'order_by': 'orderBy'
    }

    def __init__(self, ranks=None, links=None, order_by=None):  # noqa: E501
        """SubgraphTemplate - a model defined in Swagger"""  # noqa: E501

        self._ranks = None
        self._links = None
        self._order_by = None
        self.discriminator = None

        if ranks is not None:
            self.ranks = ranks
        if links is not None:
            self.links = links
        if order_by is not None:
            self.order_by = order_by

    @property
    def ranks(self):
        """Gets the ranks of this SubgraphTemplate.  # noqa: E501


        :return: The ranks of this SubgraphTemplate.  # noqa: E501
        :rtype: list[list[NodeInfo]]
        """
        return self._ranks

    @ranks.setter
    def ranks(self, ranks):
        """Sets the ranks of this SubgraphTemplate.


        :param ranks: The ranks of this SubgraphTemplate.  # noqa: E501
        :type: list[list[NodeInfo]]
        """

        self._ranks = ranks

    @property
    def links(self):
        """Gets the links of this SubgraphTemplate.  # noqa: E501


        :return: The links of this SubgraphTemplate.  # noqa: E501
        :rtype: list[LinkInfo]
        """
        return self._links

    @links.setter
    def links(self, links):
        """Sets the links of this SubgraphTemplate.


        :param links: The links of this SubgraphTemplate.  # noqa: E501
        :type: list[LinkInfo]
        """

        self._links = links

    @property
    def order_by(self):
        """Gets the order_by of this SubgraphTemplate.  # noqa: E501


        :return: The order_by of this SubgraphTemplate.  # noqa: E501
        :rtype: list[str]
        """
        return self._order_by

    @order_by.setter
    def order_by(self, order_by):
        """Sets the order_by of this SubgraphTemplate.


        :param order_by: The order_by of this SubgraphTemplate.  # noqa: E501
        :type: list[str]
        """

        self._order_by = order_by

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, SubgraphTemplate):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
