# coding: utf-8

"""
    Habitat repository and authorization API

    Habitat API  # noqa: E501

    OpenAPI spec version: V1.1.0
    Contact: zives@seas.upenn.edu
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import pennprov
from pennprov.models.prov_edge_model import ProvEdgeModel  # noqa: E501
from pennprov.rest import ApiException


class TestProvEdgeModel(unittest.TestCase):
    """ProvEdgeModel unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testProvEdgeModel(self):
        """Test ProvEdgeModel"""
        # FIXME: construct object with mandatory attributes with example values
        # model = pennprov.models.prov_edge_model.ProvEdgeModel()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
