# coding: utf-8

"""
    Habitat repository and authorization API

    Habitat API

    OpenAPI spec version: V0.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.apis.provenance_api import ProvenanceApi


class TestProvenanceApi(unittest.TestCase):
    """ ProvenanceApi unit test stubs """

    def setUp(self):
        self.api = swagger_client.apis.provenance_api.ProvenanceApi()

    def tearDown(self):
        pass

    def test_get_connected_from(self):
        """
        Test case for get_connected_from

        Get the outgoing neighbors of the given prov token
        """
        pass

    def test_get_connected_to(self):
        """
        Test case for get_connected_to

        Get the incoming neighbors of the given prov token
        """
        pass

    def test_get_edges_from(self):
        """
        Test case for get_edges_from

        Get the outgoing edges of the given prov token
        """
        pass

    def test_get_edges_to(self):
        """
        Test case for get_edges_to

        Get the incoming edges of the given prov token
        """
        pass

    def test_get_provenance_data(self):
        """
        Test case for get_provenance_data

        Get the tuple associated with a provenance token
        """
        pass

    def test_get_provenance_location(self):
        """
        Test case for get_provenance_location

        Get the location of a provenance token
        """
        pass

    def test_get_provenance_nodes(self):
        """
        Test case for get_provenance_nodes

        Get the provenance graph's nodes
        """
        pass

    def test_store_provenance_link(self):
        """
        Test case for store_provenance_link

        Store a provenance link between tokens
        """
        pass

    def test_store_provenance_node(self):
        """
        Test case for store_provenance_node

        Store a provenance token with its location
        """
        pass


if __name__ == '__main__':
    unittest.main()
