# coding: utf-8

"""
    Habitat repository and authorization API

    Habitat API

    OpenAPI spec version: V0.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.models.field_model import FieldModel


class TestFieldModel(unittest.TestCase):
    """ FieldModel unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testFieldModel(self):
        """
        Test FieldModel
        """
        # FIXME: construct object with mandatory attributes with example values
        #model = swagger_client.models.field_model.FieldModel()
        pass


if __name__ == '__main__':
    unittest.main()
