# coding: utf-8

"""
    Habitat repository and authorization API

    Habitat API  # noqa: E501

    OpenAPI spec version: V1.1.0
    Contact: zives@seas.upenn.edu
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import pennprov
from pennprov.models.prov_edge_set_model import ProvEdgeSetModel  # noqa: E501
from pennprov.rest import ApiException


class TestProvEdgeSetModel(unittest.TestCase):
    """ProvEdgeSetModel unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testProvEdgeSetModel(self):
        """Test ProvEdgeSetModel"""
        # FIXME: construct object with mandatory attributes with example values
        # model = pennprov.models.prov_edge_set_model.ProvEdgeSetModel()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
