# coding: utf-8

"""
    Habitat repository and authorization API

    Habitat API  # noqa: E501

    OpenAPI spec version: V1.1.0
    Contact: zives@seas.upenn.edu
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import pennprov
from pennprov.models.string_attribute import StringAttribute  # noqa: E501
from pennprov.rest import ApiException


class TestStringAttribute(unittest.TestCase):
    """StringAttribute unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testStringAttribute(self):
        """Test StringAttribute"""
        # FIXME: construct object with mandatory attributes with example values
        # model = pennprov.models.string_attribute.StringAttribute()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
