# coding: utf-8

"""
    Habitat repository and authorization API

    Habitat API  # noqa: E501

    OpenAPI spec version: V1.1.0
    Contact: zives@seas.upenn.edu
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import pennprov
from pennprov.models.user_info import UserInfo  # noqa: E501
from pennprov.rest import ApiException


class TestUserInfo(unittest.TestCase):
    """UserInfo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUserInfo(self):
        """Test UserInfo"""
        # FIXME: construct object with mandatory attributes with example values
        # model = pennprov.models.user_info.UserInfo()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
