# coding: utf-8

"""
    Habitat repository and authorization API

    Habitat API  # noqa: E501

    OpenAPI spec version: V1.1.0
    Contact: zives@seas.upenn.edu
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import pennprov
from pennprov.api.prov_dm_api import ProvDmApi  # noqa: E501
from pennprov.rest import ApiException


class TestProvDmApi(unittest.TestCase):
    """ProvDmApi unit test stubs"""

    def setUp(self):
        self.api = pennprov.api.prov_dm_api.ProvDmApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_store_node(self):
        """Test case for store_node

        Store a PROV DM node  # noqa: E501
        """
        pass

    def test_store_relation(self):
        """Test case for store_relation

        Store a relation between PROV DM tokens  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
