# coding: utf-8

"""
    Habitat repository and authorization API

    Habitat API  # noqa: E501

    OpenAPI spec version: V1.1.0
    Contact: zives@seas.upenn.edu
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import pennprov
from pennprov.models.link_instance import LinkInstance  # noqa: E501
from pennprov.rest import ApiException


class TestLinkInstance(unittest.TestCase):
    """LinkInstance unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testLinkInstance(self):
        """Test LinkInstance"""
        # FIXME: construct object with mandatory attributes with example values
        # model = pennprov.models.link_instance.LinkInstance()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
