# coding: utf-8

"""
    Habitat repository and authorization API

    Habitat API

    OpenAPI spec version: V0.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.models.long_field_model import LongFieldModel


class TestLongFieldModel(unittest.TestCase):
    """ LongFieldModel unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testLongFieldModel(self):
        """
        Test LongFieldModel
        """
        # FIXME: construct object with mandatory attributes with example values
        #model = swagger_client.models.long_field_model.LongFieldModel()
        pass


if __name__ == '__main__':
    unittest.main()
