# coding: utf-8

"""
    Habitat repository and authorization API

    Habitat API

    OpenAPI spec version: V0.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.models.group_details import GroupDetails


class TestGroupDetails(unittest.TestCase):
    """ GroupDetails unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGroupDetails(self):
        """
        Test GroupDetails
        """
        # FIXME: construct object with mandatory attributes with example values
        #model = swagger_client.models.group_details.GroupDetails()
        pass


if __name__ == '__main__':
    unittest.main()
