version: '3'

# The .env file is for production use with server-specific configurations

services:
  postgres:
    restart: always
    image: pennprov/hab-postgres:v1
    environment:
     - POSTGRES_USER:postgres
     - POSTGRES_PASSWORD:'habitat1'
     - POSTGRES_DB:'habitat'
    ports:
     - '5432:5432'


