# coding: utf-8

"""
    Habitat repository and authorization API

    Habitat API

    OpenAPI spec version: V0.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class ProvEdgeModel(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'endpoint_prov_token': 'str',
        'tuple_with_schema': 'TupleWithSchemaModel'
    }

    attribute_map = {
        'endpoint_prov_token': 'endpointProvToken',
        'tuple_with_schema': 'tupleWithSchema'
    }

    def __init__(self, endpoint_prov_token=None, tuple_with_schema=None):
        """
        ProvEdgeModel - a model defined in Swagger
        """

        self._endpoint_prov_token = None
        self._tuple_with_schema = None

        self.endpoint_prov_token = endpoint_prov_token
        if tuple_with_schema is not None:
          self.tuple_with_schema = tuple_with_schema

    @property
    def endpoint_prov_token(self):
        """
        Gets the endpoint_prov_token of this ProvEdgeModel.

        :return: The endpoint_prov_token of this ProvEdgeModel.
        :rtype: str
        """
        return self._endpoint_prov_token

    @endpoint_prov_token.setter
    def endpoint_prov_token(self, endpoint_prov_token):
        """
        Sets the endpoint_prov_token of this ProvEdgeModel.

        :param endpoint_prov_token: The endpoint_prov_token of this ProvEdgeModel.
        :type: str
        """
        if endpoint_prov_token is None:
            raise ValueError("Invalid value for `endpoint_prov_token`, must not be `None`")

        self._endpoint_prov_token = endpoint_prov_token

    @property
    def tuple_with_schema(self):
        """
        Gets the tuple_with_schema of this ProvEdgeModel.

        :return: The tuple_with_schema of this ProvEdgeModel.
        :rtype: TupleWithSchemaModel
        """
        return self._tuple_with_schema

    @tuple_with_schema.setter
    def tuple_with_schema(self, tuple_with_schema):
        """
        Sets the tuple_with_schema of this ProvEdgeModel.

        :param tuple_with_schema: The tuple_with_schema of this ProvEdgeModel.
        :type: TupleWithSchemaModel
        """

        self._tuple_with_schema = tuple_with_schema

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, ProvEdgeModel):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
