dbms:
 host: localhost
 graph_db: postgres
 auth_db: habitat_security
 user: postgres
 password: habitat1

provenance:
 graph: mProv-graph
 user: YOUR_USERNAME2
 password: YOUR_PASSWORD
 index: new # -> NewProvenanceStore. See pennprov/connection/dblayer.py for alternatives.

pennsieve:
 # Login to app.pennsieve,io and create an API key
 api_key: ...
 api secret: ...

qualified_names: False